### ISSUE TITLE
This extension deleted all my user settings

### ISSUE THREAD

**Issue by derekchiang** [jsaulou/vscode-theme-by-language#2] opened 2018-07-16 07:29 UTC
I installed this extension, switched themes, and then realized that all my user settings were lost.  Uninstalling this extension doesn't help.  This honestly sucks.  I've spent a lot of time curating my settings and they are gone.  Please take this extension off the marketplace until it's fixed.  Thanks.

**Comment by jsaulou** [comment] 2018-07-16 07:50
Oh man, I'm sorry :( Never had this issue.
I will take a look. I apologize for the inconvenience.

**Comment by derekchiang** [comment] 2018-07-16 07:52
If it helps, I'm using Ubuntu 18.04 and here's my vscode's info:

```
Version: 1.25.0
Commit: 0f080e5267e829de46638128001aeb7ca2d6d50e
Date: 2018-07-05T13:10:37.273Z
Electron: 1.7.12
Chrome: 58.0.3029.110
Node.js: 7.9.0
V8: 5.8.283.38
Architecture: x64
```

**Comment by jsaulou** [comment] 2018-07-16 08:45
Thank you. I'm truly really sorry. I know how it sucks to lose your settings.

**Comment by jsaulou** [comment] 2018-07-17 07:10
I couldn't reproduce the issue. Did this happen right after a vscode update?
Can you tell me the steps that lead you to this issue?

**Comment by jsaulou** [comment] 2018-09-22 09:40
I could not reproduce the issue. I close the issue for now.

**Closed by jsaulou** 2018-09-22 09:40 UTC
Labels: bug
