### ISSUE TITLE
Add support for .ipynb files

### ISSUE THREAD

**Issue by adriantre** [jsaulou/vscode-theme-by-language#10] opened 2019-10-28 13:13 UTC
Now that [vscode supports working with jupyter files](https://towardsdatascience.com/jupyter-notebook-in-visual-studio-code-3fc21a36fe43) directly, it would be great to have support for it as well. My prefered default theme does not look nice with jupyter files, and this extension would be the perfect solution!

**Comment by jsaulou** [comment] 2019-10-28 16:39
Hello ! Thanks for your interest.
Issue #8 is very similar. I will mark this issue as a duplicate and address it there.

Duplicate of #8

**Comment by jsaulou** [comment] 2019-10-28 16:40
Duplicate of #8

**Closed by jsaulou** 2019-10-28 16:39 UTC

**Comment by adriantre** [comment] 2019-10-28 17:12
Ah, sorry about that!

**Comment by jsaulou** [comment] 2019-10-29 14:54
No worries :)
